name: CI/CD - Deploy Flask API to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest > result.log || true
          cat result.log

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: pytest-result
          path: result.log

  deploy:
    name: 🚀 Deploy to Railway
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy with Railway
        run: railway up --service health-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
