name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t health-api .

    - name: Save Docker Image to File
      run: docker save health-api | gzip > health-api.tar.gz

    - name: Copy Docker Image to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "health-api.tar.gz"
        target: "~/"

    - name: Deploy on VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker load < ~/health-api.tar.gz
          docker rm -f health-api || true
          docker run -d --name health-api -p 80:80 health-api
